apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    description: Configuration Map for gateway
data:
  accept.license: {{ .Values.gateway.license.accept | quote}}
  {{- if (.Values.hazelcast.enabled) }}
  extra-java-args.env: {{ template "gateway.java.args" }} -Dcom.l7tech.server.extension.sharedCounterProvider=externalhazelcast -Dcom.l7tech.server.extension.sharedKeyValueStoreProvider=externalhazelcast -Dcom.l7tech.server.extension.sharedClusterInfoProvider=externalhazelcast
  {{- else }}
  extra-java-args.env: {{ template "gateway.java.args" }}
  {{- end }}
  ssg-jvm-heap.env: {{ .Values.gateway.heapSize }}
  log-override-properties: |+
    handlers = com.l7tech.server.log.GatewayRootLoggingHandler, com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler
    com.l7tech.server.log.GatewayRootLoggingHandler.formatter = com.l7tech.util.JsonLogFormatter
    java.util.logging.SimpleFormatter.format=
    com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler.formatter = com.l7tech.util.JsonLogFormatter
    com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler.level = CONFIG
  hazelcast-xml: |+
    <hazelcast-client
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
     http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.10.xsd"
        xmlns="http://www.hazelcast.com/schema/client-config">
     
        <instance-name>gatewayHazelcastClient-{{ .Release.Namespace }}</instance-name>
        <network>
            <cluster-members>
                <!-- Set your Hazelcast server node addresses here -->
                <address>gw-hazelcast.{{ .Release.Namespace }}.svc.cluster.local:5701</address>
            </cluster-members>
            <connection-attempt-limit>10</connection-attempt-limit>
            <redo-operation>true</redo-operation>
        </network>
     
        <connection-strategy async-start="false" reconnect-mode="ON" />
    </hazelcast-client>