apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgDQeuQWex98roX6k2UrYdn5+uWA5RsxTAok4zvRjURvSYEl/K2Nr+BNujUBfcvUY7sWtVsen7afrZrfVXaqKpNcvxTZmA6yfmF0Iu6ko5VftmUxCwKBwNvmZdIh1E0wHNHwNZ0m02srwY+T5zyDm7JPa/gPd00cg1KjkP2+TGXItiRr/1Bv0iIPBmro0eVmar5maIpfily2ZsA/NqcTevY39QWLQujmqL5O0pDgYYjSo29W5/pB/oNJxkAUS33T6R6z627i3tMbF/fmAj0yn3jyvJn8rnJlZrJocpJjEDSxnNQNj+U+0DDDsmOEFb+WoEteUgYB+zqr7klDif4gabEGMpFyq7UWqeKIPMaCwuu8ibRb3S5S+MpW/BC6KlQun0L6Xe6qV9a3MSbad+Psbrwse96LOd2drYlIK+4drY5sGuxvAsxYbnjKXrCbfwcK6ZuibeAQPteSxQg4vVHjw6X9raa4yNgcx8DtitVFaG5+VZyxh7LcClI7BIZQBiNT/46HLLu1HsP/MPHzbEeEFE0EOKFHEjBHEqkOJZ3rhW2wwmIv2oBKQi+8FLJtFTVXOTLYPgw2A2TCY3EIn2HBlxrYIN1LkwRV9sGVC6vnnf5NcH+1/BYtXIwSPHX2iVhwsbBP0SRCxNQ1QL3mKWpy6YWH2z4Y0EV0YJAEvBpxzXeD+OHmzMXSt5bdLV0Q7q2b2zK56m5QHziUtvgoml3iqjcnJInALdg7vyxZQRtaDkohC+v+x6aHrIhQenB9

