apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBa0lEFGbstxIZlmQiNGOYdGIjS0Kh+T0pK331XZ7axwPNNGbbii4N3+VoJadQk7jGXexCpbvGSkdIj5hmH3ru9SZBhdwQpArmimh9/4zjULtBMwK1qC5XSlEs0jWaH8yJbvrDmpnzjyZv3rkb1l1sF5cuW6PLaveUTxFVJPCRLNGGSt+1b5TrKbKqd+grFxndQnkWf2KFfjvIqi1q6NPXJCQIJMZz/IDeozo0HLXLTsTNXDldH1i3FjINFlaE4axb6B17V6u/Wpj/SPmXsTkN03RzICFs/J/KE1wuvGYH3feb1CUE6lMX+CUx4I+yn2yYPLA3O8jji85zU2Ubb3daokoOU16mWTWMZ7MlLHIvAvxCRRumBKcw83h0xJ4BfV8SjAzH4DNIToE7r4iSBYIYwG+zRqFoC0zDyCfIedt66IXaZstxVtaVTf07ChQeY/tEDmTR0Lexh3+HdQ9ruMAD3WwIo1w1RyPlqIjik4oJIX4dx3CmDg0sM6BH37Q+1jFjxPiTt/LhFYOU2yg3iUpJf/xjuujljHOXON2yAVijaKp6QKGcyKTxiEY2FSljEbvX1/+9txQph7vlN5fCjeuw2kIxyF50hSWfi9d1opPta3rfGIzjm6FFwMpQK6zUOp++gAo9YkC29KJfoI8YzHffE98EIUC6weHaCmbW3tEBQDZK5lRJkI6L/yweNNj/eIWtBBtEIIE9lUkv1Ha6XNsBA0mAGntNtPdoFjgyTtyYAgzun4zeMdpbh6iWMNQBT

