apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgA6ZlVIZIsE4K7ekstxSVNlsHd3zhoOyUBrq/PkP5vZbAV0n0hizAs+Fe9GtX+CpwmgNzRZgPevUj5v9zW+uedGrKDKALa7whKfrkSkFZ2RD7nBL6AZ3Wrvy4EvZRgEakml2uwfLSfak/WgtTyUNFhkJ78J0G/mSItJI85BBdM8TmZJbVZBPVSCcrMYo7+4YZZDQ5osMK1VInVXj3Ku1ZG5X4ia5pJFeqkNq8W+UxnDz1BPJKZ4LcJujAaIuSO1yxPaQXbWlLTPJ0uNfdCj/0KMZY0Bomt0ThraxcjFQK+Sx/2zBVXDnOQgINeBNtTfMzDQ5RY6NyKdaCqxOsTKhVHLiE+0lATJT8SEGyPWlYUVSusG0IigQkAEp5f64+mwRMoT2OjDsjsGkiLq4M0ftjGIGNTeNYiE+Y71VXyOQPgROLdDpwbBJu+1vTfEY9viGDAGTGY/FkaLoa1lq29iBAscCwXcEkk4utJ9CvObXxyoTR4hkn31H+l+pacH/DDxWcNTYmZkPWZn5hLDJ3PfPqlHligmWZsiBcGJDitnEQ3GFY8b8p46/vp5EXRcURvsBJfikHYCcLWxkkpdDclOuhuUco91CuqcEAUILj2NLysPJVz3jZ/mjeb2IXn6C0y9GbG6cd0Jwr4QK1pHa+Cyzw4MVsWxxASAAg5VFBlmUtVU/+8e47NacgN0wynv/tbU//d/L9walfFwEgqR0WFPfKUmMF1MTETAEhj5MD4c+qFw1CxoB7EXuh2HwQ==

