apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAGYaSKY3G1el3U9XDjyt1wtHH2y6rU9dkfpPx3Y6SipGygx2sMwI1aneVlgRnBXCZGA8WOWpfH4lwA2aZG4tMQz+wXaB5LbWEy48NxBAgCNFAJhNJXDh+38ILR6Ib4hnnKeMqS/vqtzq9dPe7/MTnKSKWdRb4eQ0DeHpjXaKlotLCgWps1IVSy/xpX7FQ/8nTD7yhzX8heHHyKLwP5gb44PNWF0YFWeXIxi7tuqxUb+21IGjnGNE6Sd0pp7MhrqwfwPwqoJ7y0oEQcBUdfhqWaj91YQ7GOwWzpBAUOK3SRfhQi5unT0GuM1hh+sIvGx4pmDEUJxHDl+HHqWKkQS8rrKjpkKg1PKlO91W+l3i+hGxd+L/pIACS5yYoTaVqqs1YbFAQ706G64m/ePuYCqQhNs6PdCuhvP3R5cm0iFc1PFOb7yw1LRSxADNss7xk7DmSSomRIPX+tYNrcCBrk57BhQ/gyZPOEwxkwS4jsq5R4WhzPICBMj3f1tSnVgBNCcOzcPm7Rb0smCV6u3/n2DY0XCyxoOPbesYcKeflmtWTSjsMwENQtDPP09IlsM6gF8FzG65wikDnpVGvoQO4vQryoHVDdb9F6lEp6T+AO5jnTPF+3hidamTugSZd0coWYLITmGCxxZHAP3JOOtSdBAlFt4umtECqjj1XbmwTa8QgLVcFHo5ZuxV7anq80+oktWxr2jERuJMnIdRV1IGIdlpVSr3p1hF5i8nJN87wlByqxj3NP+95btt5/EQ==

