apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: prod
spec:
  encryptedData:
    image-creds.yaml: AgAELuErLaozJXsiZwq8vO4WwF/+pk43YFPs38uZsjesyFv5JJnZvBrG+D0lJ2XK4bvYVRxexk1b9SMKjAfEDlt3NMTbvoCIgrdfKADlQyWJd5vUOjdwXpxKrlJ36dwmfDKUzf58U+rjV4wITGO2V9/8veoTQ1k6/oeSxF+sS9jFoe6CWkxgxxyNcLdsKncSfp06J6jnMs5hUwOAQ4NcwEbetHPXoila1Rhecmo6ySk9lFtF90RYlJcPbqTPKhSfozeDzeZjGtZUjY46T345hCyHeSbs3jSMaBIb0GWwRdYNEDgIKJxtpeAvACFyTnpdViyFm2mTtMGCwmQjeOKpj8lt91yTK2car646sVIzJ6pjY36suHeFSLkYcMXodE/S2lz2JyoY+dckf89/YChpb8JIZR44FPW4n20SPKz/+pSPqMdp8aGSP/fiytjO3Kgs+8nvPxOMiVEhtCVKi2fLZcC9Q72AbBJ2jmSh1SSc/ZhWg0yzKAc5rGgk43IHvaUr8hQUR/8bb8dahtdjuwbhmkyfbWE2IhQd/MXOD6xWZAKy7aj1UkvSX5TQOqy2wft1zVnP7bgaOCDZdvfqGkUOvoMtNDO+dR3vQAUPaH2K5aX8oy3M9gALL0nhZL9bNft6aCidHvSRwwCVcBsY0oy/8nYTYJ4skF624+Qh9OpeInC29fLY9JsePMkU41R71ntBNO9D/twyOmxBzhVxQK1ZeBFcQJeLz86qTibNnpUDFwBOyaivs4A/Tnz3KA==

