apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: prod
spec:
  encryptedData:
    image-creds.yaml: AgDLpaZxychBYGFxoWuB+hTPpqrFO9+CEM4mb/diL/A3QqDRoNvF1pOBtvLXf58WLsvjqFOXjrxfaYaQ1cevzNiF/yEhqU0Zfq6s2+LWpjkRY2n6F/f4LXTGcJW8Kn0bI6k6r89Tnl9aWn0FBcxin9TQNYdFevjKtO9C8OBi36ueCG8y+vd0EOPzgwOtY5xTmTgcXoZV6g46VWiBdLcszlRPDs38UqdQH4sIfG+zwqkD4AdlIkFCyNgSYdZ/XGH7Av1UrFitV3XmPwttSxzpUqav2TikCBg/OIqwuexC8TxoAE24urxDXiLdoRsy81GHQprhsYjxW/VEKIPcO0znwSk9KqPdIYqeFYqYMQnFYGxATZSWZHstAGD00shssZVjLgo8b58L/mgEqdZMOduHZG+2nKFlKZtiCJ0BHWq09C0LEkKtZnDq5bPGWgZA4glx26DuLeR4o1AyLv8hkDDWfEdTlAFv6unFaJwZLtnTkizy1EzimuUALk9nETqWmKcf6nZDG6SlfVtXX89urB+WV12mdK9TgU8Q1JKztB4NiTpFQY+HJmdy9GBLHpnnIweGlKBMPXswW+z20itA265AIGYiki6p9wSUEen8mQUoRwnKgsNtJflbdYPL5AEoyHb7zrqVGaCegU7+yyXsglG5QiDWuhkdO18ej3QsKyalE4uhgt88SH8OU++yJSeEUGt4u8td0xZ5RLezKNQMJKGTGCHpArz83OM5beZ7+oizuno2kbBG5ttfbmcpp4+a+zzn

