apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: prod
spec:
  encryptedData:
    image-creds.yaml: AgCbilfiUcOpYUoyo/wjFFcwl9N6jpClk+vJROz8ZnHNvA0V7kb9JdK6wWMFT/eXGApj9eEHyzBIBhdhNwSJobn/IgWracClfeCFIlK9xv/LlyEVht0GC69Tt7XfAp1uG03aiVu/zhpeWkPyOq80rkewFipzGmFMURjkW16ktaw8Gh1LEokiKN0dCIidF/w7RG8a7EOa8nxveCHCMoBezXPNkoZdhpW0J7Ac0MAN5ZT/pHYeVuaVh6qoNFUaWIr5SIG6xtS4AWBLEkk9V5BDZ2noTjlxYgLx3s1K5eDyZs3xX2iyTlgsfcuQwm5hZf0eZIutwaaRGjWCWeEBbs2U0kznnpcl2XcdbVVQiGnasZxa/dLG72MrCU+CWqMyg6FYy2Ahk1IhoW2apH4r14nqtZr/Ql0YZLjl2a0oCkGAN8VlzR9rLMnNkHeNSeyyBfVT1/HKfu14xjz7O4nkcgEo99R0nwG0Lelaa+ZPT5b7RSf0lwGGLfma0G62+NM+GUoSDqeu0p04Tw9zPlqiMmXXp+A2jZkQyAl8FEasUr0QHZCS5ZJ20pnw6aazunXjJRoYK5pW1+NZWAOdynY7Rz1JFDn6bqKOUr+ihgOzt/9b7DI83FTMEzBSITU+n1IJhyueUf/YATjpI+31yWS81vRDBShbb/huIiM5LqJAbYzWRo0qDIxu+EmHnnc6XLZX5sWw3xTm9FKkGKxgjZ7BiOvuRfLau4FWngdiZYkrFxEEsP8tLORCWiNepekQW3To

